import { register } from "./login";
import { sendVerificationCode } from "./user";
import { userInformation } from "./my";
import { userChannel } from "./home";
import { listData } from "./art-list";
import { userAllTab, loggedInToAdd, deleteUserChannel } from "./channel";
export const registerAPI = register;
export const sendVerificationCodeAPI = sendVerificationCode;
export const userInformationAPI = userInformation;
export const userChannelAPI = userChannel;
export const listDataAPI = listData;
export const userAllTabAPI = userAllTab;
export const loggedInToAddAPI = loggedInToAdd;
export const deleteUserChannelAPI = deleteUserChannel;
